#spring.application.name=hello-spring-cyj

#logging:
#  level:
#    root: info


# JDBC 설정 및 JSP 경로 추가
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: hello-spring-cyj
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: SPRING_BOOT
    password: 1234
mybatis:
  config-location:  classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/ktdsuniversity/edu/cyj/**/dao/mapper/*.xml

